name: Main Workflow.

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-called-maven-workflow:
    uses: ./.github/workflows/called_maven_workflow.yml
    with:
      mavenPomFile: 'pom.xml'
      options: '--settings settings.xml'
      testRunTitle: 'IBP Data Query'
